export const brickProducts = [
  {
    id: 1,
    name: "Khaki Matt",
    collection: "Heritage",
    color: "Tan",
    colorHex: "#C4A57B",
    manufacturer: "Austral",
    finish: "Matt",
    size: "Standard 230×76×110mm",
    weight: "3.2 kg",
    compressiveStrength: "20 MPa",
    waterAbsorption: "8%",
    frostResistance: "F2",
    description:
      "A warm khaki matt finish brick with earthy tones, ideal for heritage-inspired residential and commercial projects. Its subtle texture and warm palette complement both traditional and contemporary architecture.",
    applications: ["Residential", "Heritage Restoration", "Landscaping"],
    code: "AUS-KM-001",
    inStock: true,
    featured: true,
  },
  {
    id: 2,
    name: "Heritage Red",
    collection: "Heritage",
    color: "Red",
    colorHex: "#A0563B",
    manufacturer: "Austral",
    finish: "Matt",
    size: "Standard 230×76×110mm",
    weight: "3.4 kg",
    compressiveStrength: "25 MPa",
    waterAbsorption: "7%",
    frostResistance: "F2",
    description:
      "A rich, deep red heritage brick with natural texture variation. Perfectly suited for restoration projects and new builds that demand authentic character.",
    applications: ["Heritage Restoration", "Residential", "Commercial"],
    code: "AUS-HR-002",
    inStock: true,
  },
  {
    id: 3,
    name: "Burnt Sienna",
    collection: "Heritage",
    color: "Red",
    colorHex: "#9B4A36",
    manufacturer: "PGH",
    finish: "Rough Texture",
    size: "Standard 230×76×110mm",
    weight: "3.5 kg",
    compressiveStrength: "22 MPa",
    waterAbsorption: "9%",
    frostResistance: "F1",
    description:
      "Deep sienna tones with a rough-textured surface that evokes the warmth of traditional Australian brickwork. A timeless choice for statement walls.",
    applications: ["Feature Walls", "Heritage", "Residential"],
    code: "PGH-BS-003",
    inStock: true,
    isNew: true,
  },
  {
    id: 4,
    name: "Hawthorn",
    collection: "Modern",
    color: "Tan",
    colorHex: "#B8956A",
    manufacturer: "Bowral",
    finish: "Smooth",
    size: "Standard 230×76×110mm",
    weight: "3.1 kg",
    compressiveStrength: "30 MPa",
    waterAbsorption: "6%",
    frostResistance: "F2",
    description:
      "A refined smooth-finish brick in warm tan, bringing a contemporary edge to classic tones. Ideal for modern residential and boutique commercial builds.",
    applications: ["Residential", "Commercial", "Feature Walls"],
    code: "BOW-HW-004",
    inStock: true,
    featured: true,
  },
  {
    id: 5,
    name: "Hawkesbury Velour",
    collection: "Velour",
    color: "Gray",
    colorHex: "#9E9284",
    manufacturer: "Bowral",
    finish: "Velour",
    size: "Standard 230×76×110mm",
    weight: "3.0 kg",
    compressiveStrength: "28 MPa",
    waterAbsorption: "6.5%",
    frostResistance: "F2",
    description:
      "Soft, velvety grey tones with a distinctive velour finish that adds depth and sophistication. A premium choice for contemporary residential builds.",
    applications: ["Residential", "Commercial", "Interior Cladding"],
    code: "BOW-HV-005",
    inStock: true,
  },
  {
    id: 6,
    name: "Hawkdale Velour",
    collection: "Velour",
    color: "Gray",
    colorHex: "#B5ACA3",
    manufacturer: "Bowral",
    finish: "Velour",
    size: "Standard 230×76×110mm",
    weight: "3.0 kg",
    compressiveStrength: "28 MPa",
    waterAbsorption: "6.5%",
    frostResistance: "F2",
    description:
      "A lighter companion to the Hawkesbury range, with a pale grey velour surface. Brings an airy, refined aesthetic to feature walls and full facades.",
    applications: ["Residential", "Feature Walls", "Commercial"],
    code: "BOW-HDV-006",
    inStock: true,
    isNew: true,
  },
  {
    id: 7,
    name: "Colonial Red",
    collection: "Classic",
    color: "Red",
    colorHex: "#A04941",
    manufacturer: "Austral",
    finish: "Matt",
    size: "Standard 230×76×110mm",
    weight: "3.3 kg",
    compressiveStrength: "22 MPa",
    waterAbsorption: "8.5%",
    frostResistance: "F1",
    description:
      "A classic colonial red brick with authentic tonal variation and a matt finish. The quintessential choice for Australian residential builds and extensions.",
    applications: ["Residential", "Extensions", "Heritage"],
    code: "AUS-CR-007",
    inStock: true,
  },
  {
    id: 8,
    name: "Charcoal Smooth",
    collection: "Modern",
    color: "Charcoal",
    colorHex: "#545454",
    manufacturer: "Bowral",
    finish: "Smooth",
    size: "Standard 230×76×110mm",
    weight: "3.2 kg",
    compressiveStrength: "35 MPa",
    waterAbsorption: "5%",
    frostResistance: "F2",
    description:
      "Striking charcoal smooth finish for the bold, contemporary statement. Pairs beautifully with timber and glass for a sophisticated modern aesthetic.",
    applications: ["Contemporary Residential", "Commercial", "Feature Walls"],
    code: "BOW-CS-008",
    inStock: true,
    featured: true,
  },
  {
    id: 9,
    name: "Sandy Beige",
    collection: "Classic",
    color: "Tan",
    colorHex: "#D2B895",
    manufacturer: "Austral",
    finish: "Matt",
    size: "Standard 230×76×110mm",
    weight: "3.1 kg",
    compressiveStrength: "20 MPa",
    waterAbsorption: "9%",
    frostResistance: "F1",
    description:
      "A light, sandy beige brick that captures the warmth of coastal living. Its neutral palette is endlessly versatile for both modern and traditional homes.",
    applications: ["Coastal Residential", "Landscaping", "Classic Builds"],
    code: "AUS-SB-009",
    inStock: true,
  },
  {
    id: 10,
    name: "Slate Blue",
    collection: "Modern",
    color: "Blue",
    colorHex: "#5B7C8D",
    manufacturer: "Bowral",
    finish: "Smooth",
    size: "Standard 230×76×110mm",
    weight: "3.2 kg",
    compressiveStrength: "32 MPa",
    waterAbsorption: "5.5%",
    frostResistance: "F2",
    description:
      "An extraordinary slate blue brick with a cool, mineral tone. Perfect for architects seeking a distinctive colour palette that stands apart from the norm.",
    applications: ["Contemporary Residential", "Commercial", "Feature Walls"],
    code: "BOW-SB-010",
    inStock: true,
    isNew: true,
  },
  {
    id: 11,
    name: "Terracotta",
    collection: "Heritage",
    color: "Red",
    colorHex: "#B8634F",
    manufacturer: "Austral",
    finish: "Matt",
    size: "Standard 230×76×110mm",
    weight: "3.3 kg",
    compressiveStrength: "20 MPa",
    waterAbsorption: "8%",
    frostResistance: "F1",
    description:
      "A vibrant terracotta brick that captures the earthy warmth of Mediterranean and Australian vernacular architecture. Bold colour with timeless appeal.",
    applications: ["Residential", "Heritage", "Landscaping"],
    code: "AUS-TC-011",
    inStock: true,
  },
  {
    id: 12,
    name: "Cream Pearl",
    collection: "Classic",
    color: "Cream",
    colorHex: "#E8DCC8",
    manufacturer: "Bowral",
    finish: "Smooth",
    size: "Standard 230×76×110mm",
    weight: "3.0 kg",
    compressiveStrength: "28 MPa",
    waterAbsorption: "7%",
    frostResistance: "F2",
    description:
      "An elegant cream brick with a pearl-like smooth finish. Illuminates facades with a timeless, clean look that suits both classic and contemporary settings.",
    applications: ["Residential", "Commercial", "Facades"],
    code: "BOW-CP-012",
    inStock: true,
    featured: true,
  },
  {
    id: 13,
    name: "Urban Matte",
    collection: "Modern",
    color: "Gray",
    colorHex: "#727272",
    manufacturer: "Austral",
    finish: "Matt",
    size: "Standard 230×76×110mm",
    weight: "3.2 kg",
    compressiveStrength: "30 MPa",
    waterAbsorption: "7%",
    frostResistance: "F2",
    description:
      "A contemporary grey matt brick with industrial elegance. Versatile and sophisticated, it anchors modern architectural forms with quiet authority.",
    applications: ["Contemporary Residential", "Commercial", "Industrial"],
    code: "AUS-UM-013",
    inStock: true,
  },
  {
    id: 14,
    name: "Ironstone",
    collection: "Classic",
    color: "Charcoal",
    colorHex: "#4A4A4A",
    manufacturer: "Nubrik",
    finish: "Rough Texture",
    size: "Standard 230×76×110mm",
    weight: "3.6 kg",
    compressiveStrength: "40 MPa",
    waterAbsorption: "4.5%",
    frostResistance: "F2",
    description:
      "A dense, textured charcoal brick with the rugged character of natural ironstone. Exceptional strength makes it ideal for structural and decorative applications.",
    applications: ["Commercial", "Structural", "Feature Walls"],
    code: "NUB-IS-014",
    inStock: true,
  },
  {
    id: 15,
    name: "Toffee Brown",
    collection: "Classic",
    color: "Brown",
    colorHex: "#7A5C40",
    manufacturer: "PGH",
    finish: "Matt",
    size: "Standard 230×76×110mm",
    weight: "3.3 kg",
    compressiveStrength: "22 MPa",
    waterAbsorption: "8.5%",
    frostResistance: "F1",
    description:
      "A rich toffee brown with warm undertones that create depth and character. An ideal complement to natural stone, timber, and heritage streetscapes.",
    applications: ["Residential", "Heritage", "Extensions"],
    code: "PGH-TB-015",
    inStock: true,
  },
  {
    id: 16,
    name: "Ivory Velour",
    collection: "Velour",
    color: "Cream",
    colorHex: "#EDE4D0",
    manufacturer: "Austral",
    finish: "Velour",
    size: "Standard 230×76×110mm",
    weight: "3.0 kg",
    compressiveStrength: "26 MPa",
    waterAbsorption: "7.5%",
    frostResistance: "F2",
    description:
      "A soft ivory velour finish with delicate warmth and luminosity. Brings an understated luxury to residential and commercial facades alike.",
    applications: ["Luxury Residential", "Commercial", "Interior Feature Walls"],
    code: "AUS-IV-016",
    inStock: true,
    isNew: true,
  },
  {
    id: 17,
    name: "Rose Velour",
    collection: "Velour",
    color: "Red",
    colorHex: "#C47060",
    manufacturer: "PGH",
    finish: "Velour",
    size: "Standard 230×76×110mm",
    weight: "3.1 kg",
    compressiveStrength: "24 MPa",
    waterAbsorption: "7%",
    frostResistance: "F2",
    description:
      "A blush-rose velour brick with delicate pinkish-red tones and a signature velvety surface. Distinctive and refined for premium architectural applications.",
    applications: ["Luxury Residential", "Feature Walls", "Commercial"],
    code: "PGH-RV-017",
    inStock: true,
  },
  {
    id: 18,
    name: "Basalt Textured",
    collection: "Textured",
    color: "Charcoal",
    colorHex: "#3D3D3D",
    manufacturer: "Boral",
    finish: "Rough Texture",
    size: "Standard 230×76×110mm",
    weight: "3.7 kg",
    compressiveStrength: "45 MPa",
    waterAbsorption: "4%",
    frostResistance: "F2",
    description:
      "Dark and dramatic, the Basalt Textured brick delivers maximum visual impact with its deep charcoal tones and pronounced surface texture. Built for bold architecture.",
    applications: ["Commercial", "Contemporary Residential", "Feature Walls"],
    code: "BOR-BT-018",
    inStock: false,
  },
  {
    id: 19,
    name: "Alpine White",
    collection: "Textured",
    color: "White",
    colorHex: "#E8E4DC",
    manufacturer: "Bowral",
    finish: "Rough Texture",
    size: "Standard 230×76×110mm",
    weight: "3.0 kg",
    compressiveStrength: "26 MPa",
    waterAbsorption: "8%",
    frostResistance: "F2",
    description:
      "Crisp and luminous with a natural textured surface, the Alpine White creates fresh, light-filled facades. Perfect for coastal and contemporary homes.",
    applications: ["Coastal Residential", "Contemporary Builds", "Feature Walls"],
    code: "BOW-AW-019",
    inStock: true,
    isNew: true,
  },
  {
    id: 20,
    name: "Terra Rough",
    collection: "Textured",
    color: "Brown",
    colorHex: "#8A6448",
    manufacturer: "Nubrik",
    finish: "Rough Texture",
    size: "Standard 230×76×110mm",
    weight: "3.5 kg",
    compressiveStrength: "28 MPa",
    waterAbsorption: "9%",
    frostResistance: "F1",
    description:
      "A raw, earthy brown brick with an expressive rough texture that celebrates the natural beauty of fired clay. Full of organic character and warmth.",
    applications: ["Residential", "Landscaping", "Retaining Walls"],
    code: "NUB-TR-020",
    inStock: true,
  },
  {
    id: 21,
    name: "Storm Velour",
    collection: "Velour",
    color: "Charcoal",
    colorHex: "#5C5C5C",
    manufacturer: "PGH",
    finish: "Velour",
    size: "Standard 230×76×110mm",
    weight: "3.2 kg",
    compressiveStrength: "32 MPa",
    waterAbsorption: "5.5%",
    frostResistance: "F2",
    description:
      "Sophisticated storm-dark velour finish with a tactile, velvety surface. Delivers a premium, high-end aesthetic ideal for contemporary architectural projects.",
    applications: ["Contemporary Residential", "Commercial", "Interior Cladding"],
    code: "PGH-SV-021",
    inStock: true,
    featured: true,
  },
  {
    id: 22,
    name: "Sandstone Classic",
    collection: "Classic",
    color: "Cream",
    colorHex: "#D8C9A8",
    manufacturer: "Nubrik",
    finish: "Matt",
    size: "Standard 230×76×110mm",
    weight: "3.1 kg",
    compressiveStrength: "24 MPa",
    waterAbsorption: "8%",
    frostResistance: "F1",
    description:
      "A warm sandstone-toned brick that captures the essence of Australia's historic built environment. Subtle variation and natural matt finish for authentic character.",
    applications: ["Heritage Restoration", "Classic Residential", "Commercial"],
    code: "NUB-SC-022",
    inStock: true,
  },
];

export const collections = ["Heritage", "Modern", "Classic", "Velour", "Textured"];
export const colors = ["Tan", "Red", "Gray", "Blue", "Cream", "Charcoal", "Brown", "White"];
export const manufacturers = ["Austral", "Bowral", "Boral", "Nubrik", "PGH"];
export const finishes = ["Matt", "Smooth", "Velour", "Rough Texture"];
